### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by wanbangshucheng** [fscarmen2/X-for-Glitch#17]
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/1d7ce368-e3f8-4b07-84ff-44554e0f774a)
就配置了这几项，节点数据也正常
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/5790e8c9-5908-40df-bcf0-b45895a52d75)
系统进程表如下
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/a9028886-879d-4ac6-a6f7-6f624def7ee1)
但是有延迟无速度，一开代理就显示-1，如下图
![O46W)}XHQT (`UXTUZB8%CG](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/f439bd8c-9476-493b-bd9a-55e3344b896c)
报错
启动服务：初始化入站：配置tun接口：当文件已经存在时，无法创建该文件。
我该如何解决该问题，谢谢大佬

**Comment by fscarmen2** [comment]
对于这些问题，真是不想回复的

<img width="1077" alt="image" src="https://github.com/fscarmen2/X-for-Glitch/assets/92626977/e40982da-9402-4535-b57d-4346e944ce0d">

**Comment by wanbangshucheng** [comment]
很抱歉打扰您了，我使用了默认值
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/1521c165-019a-401d-9792-c4f623b50f91)
在Android客户端上有延迟，
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/faad40d7-523e-41a0-81f8-fc863bd1ef47)
但依旧无法连接
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/a25210a1-de20-4218-ae95-72b83f6503e4)
在Windows端测试有延迟，只要一开代理马上变-1
![Uploading image.png…]()
报错[31mERROR[0m [[38;5;218m1188853450[0m] inbound/tun[tun-in]: read udp 172.19.0.2:53: connection was refused | upstream: context canceled

**Comment by fscarmen2** [comment]
你进入 glitch 的后台，在终端处运行 `ss -nltp` 看看服务起来没有

<img width="1680" alt="image" src="https://github.com/fscarmen2/X-for-Glitch/assets/92626977/0bd11b48-cb3e-44c3-b63a-2ae9c9ab1ee0">

**Comment by wanbangshucheng** [comment]
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/cbdeb4d6-32b8-410c-a04d-e6187cde5c68)
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/4dda9b84-38ed-476a-ad71-c711a2af6c78)
提示这样子，我应该怎么处理

**Comment by fscarmen2** [comment]
看截图，你的xray和argo都正常运行了，你运行以下的，把回显发我看看 fscarmen@gmail.com
```
cat config.json
wget -qO- http://$(ss -nltp | awk '/cloudflared/ {print $4}')/quicktunnel
```

**Comment by wanbangshucheng** [comment]
已发送邮件到你的邮箱。非常感谢你帮助我解决问题。

**Comment by fscarmen2** [comment]
你是用临时 tunnel 的，还是用json或者token方式？

**Comment by wanbangshucheng** [comment]
我使用的应该是临时 tunnel，我没有配置token，原因是我发现需要绑定银行卡才能继续。

**Comment by wanbangshucheng** [comment]
我尝试了进行如下设置
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/dcabe623-45e3-44e5-9570-0971ff67975c)
但是di点击之后跳转的页面无法继续操作了
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/84709698-7c54-4c49-9dc0-fe2b48d9b347)
我是小白，第一次搭建这个，还望多多帮助。

**Comment by wanbangshucheng** [comment]
并且点击“隧道”后提示需要绑定银行卡选择计划才能继续
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/2d021b0f-650c-4fc3-92cd-3cfb9b05bf37)

**Comment by fscarmen2** [comment]
你没有域名的吗？去 eu.org / nom.za 这些平台申请个免费的，这些都要要审比较长时间，可能是一头半个月的，又或者你买个域名了。

**Comment by wanbangshucheng** [comment]
第一次搭着个，主要是学习用途，之前确实没有申请过域名，那我去申请一个.
第一个网站之前试过，一直注册注册不上去，提示用户名无效
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/79a51c68-ecf0-483e-938b-d2000006ba44)
我试试第二个吧，等待域名批准下来再看看

**Comment by fscarmen2** [comment]
这个是首年免费的：https://www.dynadot.com/register-your-free-link-domain  

https://secure.nom.za 的话，你申请的域名，要与你认证的名字一样，至少相近才能过的

eu.org 人工审批时间不好说，有可能长达1个月的，不过就一定能过的。

**Comment by wanbangshucheng** [comment]
我已经成功申请dynadot一年免费域名，并且设置了argo json。但是当服务重启后，节点还会变动，就算挂了保活第二天还是会重启......
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/d53040d7-e1d3-4826-9906-e76a69198a07)

**Comment by fscarmen2** [comment]
看你之前的截图是填错了， ARGO_AUTH 是不包含域名，从 { 。。。 } 开始的。

**Comment by wanbangshucheng** [comment]
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/7df5edc3-f5c0-4312-b0a8-9b39e040c223)
刚才细看了一下，有多个域名以及{ 。。。} ，我是否只需要填一个如下图所示即可呢
![image](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/48cf8455-0cf3-4fcd-ad5c-c132f1b472cc)

**Comment by wanbangshucheng** [comment]
![Screenshot_20230924_120920](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/35bb9843-1a17-4a4d-b267-e257df5f1157)
现在光配置这些用不了吗

**Comment by xlee2020** [comment]
请教一下
运行后节点一直-1
ss -nltp 发现web.js没有运行起来
其它3个服务都起来了
我应该从哪里找问题？
感谢！

**Comment by fscarmen2** [comment]
> 请教一下 运行后节点一直-1 ss -nltp 发现web.js没有运行起来 其它3个服务都起来了 我应该从哪里找问题？ 感谢！

手动运行一下，看有什么提示。

**Comment by xlee2020** [comment]
您说的 手动运行 我chatGPTl了一下，是不是这个意思
$ node web.js
/app/web.js:7
<!DOCTYPE html>
^

SyntaxError: Unexpected token '<'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47

**Comment by fscarmen2** [comment]
> 您说的 手动运行 我chatGPTl了一下，是不是这个意思 $ node web.js /app/web.js:7
> 
> ^
> 
> SyntaxError: Unexpected token '<' at wrapSafe (internal/modules/cjs/loader.js:1001:16) at Module._compile (internal/modules/cjs/loader.js:1049:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) at Module.load (internal/modules/cjs/loader.js:950:32) at Function.Module._load (internal/modules/cjs/loader.js:790:12) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) at internal/main/run_main_module.js:17:47

```
./web.js -c ./config.json
```

手动运行一下，看有什么提示，注意两个文件都上传上去了。

**Comment by xlee2020** [comment]
$ ./web.js -c ./config.json
./web.js: line 7: syntax error near unexpected token `newline'
./web.js: line 7: `<!DOCTYPE html>'

**Comment by xlee2020** [comment]
![1697210379654](https://github.com/fscarmen2/X-for-Glitch/assets/57035733/ed15bfe5-a68f-4db2-a1e5-b3d9a2327f9e)

**Comment by fscarmen2** [comment]
> ![1697210379654](https://user-images.githubusercontent.com/57035733/274942982-ed15bfe5-a68f-4db2-a1e5-b3d9a2327f9e.jpg)

```
cat ./config.json
```

**Comment by xlee2020** [comment]
你好 附上config.json副本
感谢！

fscarmen2 ***@***.***> 於 2023年10月13日 週五 下午11:43寫道：

**Comment by wanbangshucheng** [comment]
> ![1697210379654](https://user-images.githubusercontent.com/57035733/274942982-ed15bfe5-a68f-4db2-a1e5-b3d9a2327f9e.jpg)

我也是这样
![Screenshot_20231106_171932](https://github.com/fscarmen2/X-for-Glitch/assets/115765860/06d42ea8-e565-4c79-a268-10ff9cfa7aba)
你是怎么结局的呢
